### ISSUE TITLE
4x5MacroPad PCB Project files

### ISSUE THREAD

**Issue by KonniLol** [tobychui/4xMacropad#3]
Really like your design but I'd like change a few things. I've seen that you have added the json for the 4Key Pad and was wondering if you could also add the project files for the 4x5 Pad.

**Comment by tobychui** [comment]
Yes, I will open source it later after I have sell enough of them (est. around 10 - 15 units, or 4 - 5 if I mark up the price a bit higher) on Tindie to make up for the development cost of this project (and if possible, fund part of my next keyboard R&D which is a 34-key split layout keyboard). 

Delaying the release of the schematics can prevent / delay clones that manufacture them for sale before I can break-even the cost of developing new design and publishing them for free online.  As you might have notice, my goal is to try to make mechanical keyboards much more easy to make and affordable for everyone. 

Sorry that I need to keep you waiting on this. If you like, you can click the "Watch" button on the top right of the repo so when I upload the json file, you can have it asap :) 

Thank you for the understanding!

**Comment by KonniLol** [comment]
No problem, I totally understand.

**Comment by tobychui** [comment]
Closing this issue as PCB file already released
