### ISSUE TITLE
Question: Is this keypad will work on boot?

### ISSUE THREAD

**Issue by OmerFS** [tobychui/4xMacropad#4]
Hello,

Thank you for project.

Is this device able to work at the boot or bios screen?

i need to know device will work without operating system or not (bioses like mouse not activated old bioses.)

Thank you!

Omer

**Comment by OmerFS** [comment]
> Omer

**Comment by tobychui** [comment]
@OmerFS for your question: 

I don't know and I didn't tested it in bios before. 
This project is abandoned as it has already served it purpose of making this chip popular and better open source firmware has been developed by the community. There are a lot of alternative & similar products / projects out there that make use of the same chip (Ch552G). I guess you could search for a more popular & similar project and ask their users / seller instead.
